// <auto-generated />
using System;
using GreenTrace.Server.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GreenTrace.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505064228_StartUp")]
    partial class StartUp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GreenTrace.Server.Features.ActorRoles.ActorRole", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.PrimitiveCollection<long[]>("allowedStages")
                        .HasColumnType("bigint[]");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long?>("domainId")
                        .HasColumnType("bigint");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("organizationId")
                        .HasColumnType("bigint");

                    b.Property<int>("revision")
                        .HasColumnType("integer");

                    b.Property<string>("updatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("domainId");

                    b.HasIndex("organizationId", "code")
                        .IsUnique();

                    b.ToTable("actorRoles");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Actors.Actor", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("contact")
                        .HasColumnType("jsonb");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("externalId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<string>("location")
                        .HasColumnType("jsonb");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("organizationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("registeredBy")
                        .HasColumnType("bigint");

                    b.Property<string>("registrationMeta")
                        .HasColumnType("jsonb");

                    b.Property<int>("revision")
                        .HasColumnType("integer");

                    b.Property<long?>("roleId")
                        .HasColumnType("bigint");

                    b.Property<string>("updatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("organizationId");

                    b.HasIndex("registeredBy");

                    b.HasIndex("roleId");

                    b.HasIndex("organizationId", "externalId")
                        .IsUnique()
                        .HasFilter("\"externalId\" IS NOT NULL");

                    b.ToTable("actors");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Audit.AuditLog", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("changes")
                        .HasColumnType("jsonb");

                    b.Property<long>("entityId")
                        .HasColumnType("bigint");

                    b.Property<string>("entityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("occurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("organizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("userEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("userId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("occurredAt");

                    b.HasIndex("organizationId");

                    b.HasIndex("userId");

                    b.HasIndex("entityType", "entityId");

                    b.ToTable("auditLogs");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Auth.RefreshToken", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("expiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("replacedByToken")
                        .HasColumnType("text");

                    b.Property<int>("revision")
                        .HasColumnType("integer");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("updatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("userId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("token")
                        .IsUnique();

                    b.HasIndex("userId");

                    b.ToTable("refreshTokens");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Batches.Batch", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("batchCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("currentQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<long?>("currentStageId")
                        .HasColumnType("bigint");

                    b.Property<long>("domainId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("initialQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("initialUnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("metadata")
                        .HasColumnType("jsonb");

                    b.Property<long>("organizationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("originActorId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("originDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("originLocation")
                        .HasColumnType("jsonb");

                    b.Property<long?>("productId")
                        .HasColumnType("bigint");

                    b.Property<int>("revision")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("totalValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("updatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("currentStageId");

                    b.HasIndex("domainId");

                    b.HasIndex("originActorId");

                    b.HasIndex("productId");

                    b.HasIndex("organizationId", "batchCode")
                        .IsUnique();

                    b.HasIndex("organizationId", "status");

                    b.HasIndex("organizationId", "domainId", "status");

                    b.ToTable("batches");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Batches.BatchLineage", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("childBatchId")
                        .HasColumnType("bigint");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long>("organizationId")
                        .HasColumnType("bigint");

                    b.Property<long>("parentBatchId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("revision")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("updatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("childBatchId");

                    b.HasIndex("parentBatchId");

                    b.ToTable("batchLineages");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Credentials.Credential", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("actorId")
                        .HasColumnType("bigint");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("expiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("issuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("issuer")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("organizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("reference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("revision")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("updatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("actorId");

                    b.HasIndex("organizationId");

                    b.ToTable("credentials");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Domains.Domain", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("organizationId")
                        .HasColumnType("bigint");

                    b.Property<int>("revision")
                        .HasColumnType("integer");

                    b.Property<string>("updatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("organizationId", "code")
                        .IsUnique();

                    b.ToTable("domains");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Evidence.Evidence", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("credentialId")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("mimeType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("organizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("originalFilename")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("revision")
                        .HasColumnType("integer");

                    b.Property<long?>("sizeBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("stageRecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("storageKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("updatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("uploadedBy")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("credentialId");

                    b.HasIndex("stageRecordId");

                    b.HasIndex("uploadedBy");

                    b.HasIndex("organizationId", "stageRecordId");

                    b.ToTable("evidences");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Organizations.Organization", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("revision")
                        .HasColumnType("integer");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("updatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("slug")
                        .IsUnique();

                    b.ToTable("organizations");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Products.Product", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long?>("domainId")
                        .HasColumnType("bigint");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("organizationId")
                        .HasColumnType("bigint");

                    b.Property<int>("revision")
                        .HasColumnType("integer");

                    b.Property<string>("sku")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("unitOfMeasure")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("updatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("domainId");

                    b.HasIndex("organizationId");

                    b.HasIndex("organizationId", "sku")
                        .IsUnique()
                        .HasFilter("\"sku\" IS NOT NULL");

                    b.ToTable("products");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Roles.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string[]>("permissions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("revision")
                        .HasColumnType("integer");

                    b.Property<string>("updatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("GreenTrace.Server.Features.StageFields.StageField", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("dataType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("fieldOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("options")
                        .HasColumnType("jsonb");

                    b.Property<int>("revision")
                        .HasColumnType("integer");

                    b.Property<long>("stageId")
                        .HasColumnType("bigint");

                    b.Property<string>("uiHint")
                        .HasColumnType("jsonb");

                    b.Property<string>("updatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("validation")
                        .HasColumnType("jsonb");

                    b.HasKey("id");

                    b.HasIndex("stageId", "code")
                        .IsUnique();

                    b.ToTable("stageFields");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.StageRecordFields.StageRecordField", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("revision")
                        .HasColumnType("integer");

                    b.Property<long>("stageFieldId")
                        .HasColumnType("bigint");

                    b.Property<long>("stageRecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("updatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("value")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("id");

                    b.HasIndex("stageFieldId");

                    b.HasIndex("stageRecordId", "stageFieldId")
                        .IsUnique();

                    b.ToTable("stageRecordFields");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.StageRecords.StageRecord", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("actorId")
                        .HasColumnType("bigint");

                    b.Property<long>("batchId")
                        .HasColumnType("bigint");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("geoPoint")
                        .HasColumnType("jsonb");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("notes")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("organizationId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("recordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("recordedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("revision")
                        .HasColumnType("integer");

                    b.Property<long>("stageId")
                        .HasColumnType("bigint");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("unitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("updatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("validatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("validatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("validationNotes")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("id");

                    b.HasIndex("actorId");

                    b.HasIndex("recordedBy");

                    b.HasIndex("stageId");

                    b.HasIndex("validatedBy");

                    b.HasIndex("batchId", "stageId");

                    b.HasIndex("organizationId", "actorId");

                    b.HasIndex("organizationId", "batchId");

                    b.HasIndex("organizationId", "stageId");

                    b.ToTable("stageRecords");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Stages.Stage", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long>("domainId")
                        .HasColumnType("bigint");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("revision")
                        .HasColumnType("integer");

                    b.Property<short>("sequence")
                        .HasColumnType("smallint");

                    b.Property<string>("updatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("domainId", "code")
                        .IsUnique();

                    b.HasIndex("domainId", "sequence")
                        .IsUnique();

                    b.ToTable("stages");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<long>("organizationId")
                        .HasColumnType("bigint");

                    b.Property<int>("revision")
                        .HasColumnType("integer");

                    b.Property<string>("updatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("organizationId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GreenTrace.Server.Features.ValueChain.ValueRecord", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("actorId")
                        .HasColumnType("bigint");

                    b.Property<long>("batchId")
                        .HasColumnType("bigint");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<long>("organizationId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("recordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("revision")
                        .HasColumnType("integer");

                    b.Property<long>("stageId")
                        .HasColumnType("bigint");

                    b.Property<long>("stageRecordId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("totalValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("unitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("updatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("validatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("actorId");

                    b.HasIndex("batchId");

                    b.HasIndex("stageId");

                    b.HasIndex("stageRecordId")
                        .IsUnique();

                    b.HasIndex("organizationId", "actorId");

                    b.HasIndex("organizationId", "batchId");

                    b.HasIndex("organizationId", "stageId");

                    b.ToTable("valueRecords");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GreenTrace.Server.Features.ActorRoles.ActorRole", b =>
                {
                    b.HasOne("GreenTrace.Server.Features.Domains.Domain", "domain")
                        .WithMany()
                        .HasForeignKey("domainId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GreenTrace.Server.Features.Organizations.Organization", "organization")
                        .WithMany()
                        .HasForeignKey("organizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("domain");

                    b.Navigation("organization");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Actors.Actor", b =>
                {
                    b.HasOne("GreenTrace.Server.Features.Organizations.Organization", "organization")
                        .WithMany()
                        .HasForeignKey("organizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenTrace.Server.Features.Users.User", "registeredByUser")
                        .WithMany()
                        .HasForeignKey("registeredBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GreenTrace.Server.Features.ActorRoles.ActorRole", "role")
                        .WithMany("actors")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("organization");

                    b.Navigation("registeredByUser");

                    b.Navigation("role");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Batches.Batch", b =>
                {
                    b.HasOne("GreenTrace.Server.Features.Stages.Stage", "currentStage")
                        .WithMany()
                        .HasForeignKey("currentStageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GreenTrace.Server.Features.Domains.Domain", "domain")
                        .WithMany()
                        .HasForeignKey("domainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenTrace.Server.Features.Organizations.Organization", "organization")
                        .WithMany()
                        .HasForeignKey("organizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenTrace.Server.Features.Actors.Actor", "originActor")
                        .WithMany()
                        .HasForeignKey("originActorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GreenTrace.Server.Features.Products.Product", "product")
                        .WithMany("batches")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("currentStage");

                    b.Navigation("domain");

                    b.Navigation("organization");

                    b.Navigation("originActor");

                    b.Navigation("product");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Batches.BatchLineage", b =>
                {
                    b.HasOne("GreenTrace.Server.Features.Batches.Batch", "childBatch")
                        .WithMany()
                        .HasForeignKey("childBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenTrace.Server.Features.Batches.Batch", "parentBatch")
                        .WithMany()
                        .HasForeignKey("parentBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("childBatch");

                    b.Navigation("parentBatch");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Credentials.Credential", b =>
                {
                    b.HasOne("GreenTrace.Server.Features.Actors.Actor", "actor")
                        .WithMany("credentials")
                        .HasForeignKey("actorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("actor");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Domains.Domain", b =>
                {
                    b.HasOne("GreenTrace.Server.Features.Organizations.Organization", "organization")
                        .WithMany()
                        .HasForeignKey("organizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("organization");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Evidence.Evidence", b =>
                {
                    b.HasOne("GreenTrace.Server.Features.Credentials.Credential", "credential")
                        .WithMany()
                        .HasForeignKey("credentialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GreenTrace.Server.Features.StageRecords.StageRecord", "stageRecord")
                        .WithMany("evidence")
                        .HasForeignKey("stageRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GreenTrace.Server.Features.Users.User", "uploadedByUser")
                        .WithMany()
                        .HasForeignKey("uploadedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("credential");

                    b.Navigation("stageRecord");

                    b.Navigation("uploadedByUser");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Products.Product", b =>
                {
                    b.HasOne("GreenTrace.Server.Features.Domains.Domain", "domain")
                        .WithMany()
                        .HasForeignKey("domainId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GreenTrace.Server.Features.Organizations.Organization", "organization")
                        .WithMany()
                        .HasForeignKey("organizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("domain");

                    b.Navigation("organization");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.StageFields.StageField", b =>
                {
                    b.HasOne("GreenTrace.Server.Features.Stages.Stage", "stage")
                        .WithMany("stageFields")
                        .HasForeignKey("stageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("stage");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.StageRecordFields.StageRecordField", b =>
                {
                    b.HasOne("GreenTrace.Server.Features.StageFields.StageField", "stageField")
                        .WithMany()
                        .HasForeignKey("stageFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenTrace.Server.Features.StageRecords.StageRecord", "stageRecord")
                        .WithMany("fields")
                        .HasForeignKey("stageRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("stageField");

                    b.Navigation("stageRecord");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.StageRecords.StageRecord", b =>
                {
                    b.HasOne("GreenTrace.Server.Features.Actors.Actor", "actor")
                        .WithMany()
                        .HasForeignKey("actorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GreenTrace.Server.Features.Batches.Batch", "batch")
                        .WithMany("stageRecords")
                        .HasForeignKey("batchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenTrace.Server.Features.Organizations.Organization", "organization")
                        .WithMany()
                        .HasForeignKey("organizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenTrace.Server.Features.Users.User", "recordedByUser")
                        .WithMany()
                        .HasForeignKey("recordedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GreenTrace.Server.Features.Stages.Stage", "stage")
                        .WithMany()
                        .HasForeignKey("stageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenTrace.Server.Features.Users.User", "validatedByUser")
                        .WithMany()
                        .HasForeignKey("validatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("actor");

                    b.Navigation("batch");

                    b.Navigation("organization");

                    b.Navigation("recordedByUser");

                    b.Navigation("stage");

                    b.Navigation("validatedByUser");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Stages.Stage", b =>
                {
                    b.HasOne("GreenTrace.Server.Features.Domains.Domain", "domain")
                        .WithMany("stages")
                        .HasForeignKey("domainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("domain");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Users.User", b =>
                {
                    b.HasOne("GreenTrace.Server.Features.Organizations.Organization", "organization")
                        .WithMany()
                        .HasForeignKey("organizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("organization");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.ValueChain.ValueRecord", b =>
                {
                    b.HasOne("GreenTrace.Server.Features.Actors.Actor", "actor")
                        .WithMany()
                        .HasForeignKey("actorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GreenTrace.Server.Features.Batches.Batch", "batch")
                        .WithMany()
                        .HasForeignKey("batchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenTrace.Server.Features.Organizations.Organization", "organization")
                        .WithMany()
                        .HasForeignKey("organizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenTrace.Server.Features.Stages.Stage", "stage")
                        .WithMany()
                        .HasForeignKey("stageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenTrace.Server.Features.StageRecords.StageRecord", "stageRecord")
                        .WithMany()
                        .HasForeignKey("stageRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("actor");

                    b.Navigation("batch");

                    b.Navigation("organization");

                    b.Navigation("stage");

                    b.Navigation("stageRecord");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("GreenTrace.Server.Features.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("GreenTrace.Server.Features.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("GreenTrace.Server.Features.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("GreenTrace.Server.Features.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenTrace.Server.Features.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("GreenTrace.Server.Features.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreenTrace.Server.Features.ActorRoles.ActorRole", b =>
                {
                    b.Navigation("actors");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Actors.Actor", b =>
                {
                    b.Navigation("credentials");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Batches.Batch", b =>
                {
                    b.Navigation("stageRecords");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Domains.Domain", b =>
                {
                    b.Navigation("stages");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Products.Product", b =>
                {
                    b.Navigation("batches");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.StageRecords.StageRecord", b =>
                {
                    b.Navigation("evidence");

                    b.Navigation("fields");
                });

            modelBuilder.Entity("GreenTrace.Server.Features.Stages.Stage", b =>
                {
                    b.Navigation("stageFields");
                });
#pragma warning restore 612, 618
        }
    }
}
