using App.AutoGenerated;
using GreenTrace.Server.Common.Data;
using GreenTrace.Server.Common.Extensions;

var builder = WebApplication.CreateBuilder(args);

// ── Database ─────────────────────────────────────────────────
builder.Services.AddData(builder.Configuration);

// ── Identity ────────────────────────────────────────────────
builder.Services.AddIdentityServices();

// ── JWT Auth ────────────────────────────────────────────────
builder.Services.AddJwtAuth(builder.Configuration);

// ── Auth Context + UserService ──────────────────────────────
builder.Services.AddAuthContext();

// ── GraphQL (CAI) ────────────────────────────────────────────
builder.addCai((opts) =>
{
    opts.ServiceName = builder.Environment.ApplicationName;
}, (gqlBuilder) =>
{
    gqlBuilder
        .AddQueryType<Query>()
        .AddAuthorization()
        .AddMutationConventions(true)
        .RegisterDbContextFactory<GreenTrace.Server.Common.Data.AppDbContext>()
        .AddFiltering()
        .AddSorting()
        .AddProjections();
});

// ── CORS ─────────────────────────────────────────────────────
builder.Services.AddCors();

AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

var app = builder.Build();

// ── Seed data (Development only) ────────────────────────────
if (app.Environment.IsDevelopment())
{
    using var scope = app.Services.CreateScope();
    await SeedData.Initialize(scope.ServiceProvider);
}

app.MapGet("/", () => $"greentrace-api Here. It is {DateTimeOffset.UtcNow}");

app.UseCors();
app.UseAuthentication();
app.UseAuthorization();
app.useCai();

app.Run();
